# Generated by Django 6.0.5 on 2026-08-08 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LateFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("days_late", models.PositiveIntegerField()),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_fees",
                        to="rentals.rentalorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LateFeeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("grace_period_days", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_fee_config",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
