# Generated by Django 6.1 on 2026-08-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
    ]
