# Generated by Django 6.1 on 2026-08-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role_merchant"),
        ("products", "0002_category_icon_category_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="accounts.merchant",
            ),
        ),
    ]
