# Generated by Django 6.1 on 2026-08-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_renter_renterlistingrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="renterlistingrequest",
            name="images_data",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
