# Generated by Django 6.1 on 2026-08-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_renterlistingrequest_images_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="condition_tag",
            field=models.CharField(blank=True, default="Good", max_length=100),
        ),
        migrations.AddField(
            model_name="renterlistingrequest",
            name="admin_condition_tag",
            field=models.CharField(
                choices=[
                    ("Good", "Good"),
                    ("Superb", "Superb"),
                    ("Does Not Apply", "Doesn't Apply"),
                    ("Custom", "Custom"),
                ],
                default="Good",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="renterlistingrequest",
            name="admin_custom_condition",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="renterlistingrequest",
            name="included_items",
            field=models.TextField(blank=True, null=True),
        ),
    ]
