# Generated by Django 6.1 on 2026-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_condition_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="renterlistingrequest",
            name="approved_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="renterlistingrequest",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="renterlistingrequest",
            name="rejected_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
