# Generated by Django 6.1 on 2026-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_available_quantity_product_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="security_deposit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
