import os

BASE_DIR = r"c:\Users\raipr\OneDrive\Desktop\odooxrental\backend-drf"
APPS_DIR = os.path.join(BASE_DIR, "apps")

apps_structure = {
    "pricing": {
        "__init__.py": "",
        "apps.py": """from django.apps import AppConfig\n\nclass PricingConfig(AppConfig):\n    default_auto_field = 'django.db.models.BigAutoField'\n    name = 'apps.pricing'\n""",
        "models.py": """from django.db import models\n\nclass PriceList(models.Model):\n    name = models.CharField(max_length=100)\n    is_active = models.BooleanField(default=True)\n    created_at = models.DateTimeField(auto_now_add=True)\n    updated_at = models.DateTimeField(auto_now=True)\n\n    def __str__(self):\n        return self.name\n\nclass RentalPeriod(models.Model):\n    name = models.CharField(max_length=50)\n    duration_hours = models.IntegerField()\n\n    def __str__(self):\n        return self.name\n\nclass ProductPricing(models.Model):\n    product_id = models.IntegerField(null=True, blank=True) # generic\n    price_list = models.ForeignKey(PriceList, on_delete=models.CASCADE)\n    period = models.ForeignKey(RentalPeriod, on_delete=models.CASCADE)\n    price = models.DecimalField(max_digits=10, decimal_places=2)\n""",
        "admin.py": """from django.contrib import admin\nfrom .models import PriceList, RentalPeriod, ProductPricing\n\nadmin.site.register(PriceList)\nadmin.site.register(RentalPeriod)\nadmin.site.register(ProductPricing)\n""",
        "serializers.py": """from rest_framework import serializers\nfrom .models import PriceList, RentalPeriod, ProductPricing\n\nclass PriceListSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = PriceList\n        fields = '__all__'\n\nclass RentalPeriodSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = RentalPeriod\n        fields = '__all__'\n\nclass ProductPricingSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = ProductPricing\n        fields = '__all__'\n""",
        "views.py": """from rest_framework import viewsets\nfrom .models import PriceList, RentalPeriod, ProductPricing\nfrom .serializers import PriceListSerializer, RentalPeriodSerializer, ProductPricingSerializer\n\nclass PriceListViewSet(viewsets.ModelViewSet):\n    queryset = PriceList.objects.all()\n    serializer_class = PriceListSerializer\n\nclass RentalPeriodViewSet(viewsets.ModelViewSet):\n    queryset = RentalPeriod.objects.all()\n    serializer_class = RentalPeriodSerializer\n\nclass ProductPricingViewSet(viewsets.ModelViewSet):\n    queryset = ProductPricing.objects.all()\n    serializer_class = ProductPricingSerializer\n""",
        "urls.py": """from django.urls import path, include\nfrom rest_framework.routers import DefaultRouter\nfrom .views import PriceListViewSet, RentalPeriodViewSet, ProductPricingViewSet\n\nrouter = DefaultRouter()\nrouter.register(r'pricelists', PriceListViewSet)\nrouter.register(r'rentalperiods', RentalPeriodViewSet)\nrouter.register(r'productpricing', ProductPricingViewSet)\n\nurlpatterns = [\n    path('', include(router.urls)),\n]\n"""
    },
    "rentals": {
        "__init__.py": "",
        "apps.py": """from django.apps import AppConfig\n\nclass RentalsConfig(AppConfig):\n    default_auto_field = 'django.db.models.BigAutoField'\n    name = 'apps.rentals'\n\n    def ready(self):\n        import apps.rentals.signals\n""",
        "models.py": """from django.db import models\nfrom django.conf import settings\n\nclass Cart(models.Model):\n    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)\n    created_at = models.DateTimeField(auto_now_add=True)\n    updated_at = models.DateTimeField(auto_now=True)\n\nclass CartItem(models.Model):\n    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)\n    product_id = models.IntegerField()\n    quantity = models.PositiveIntegerField(default=1)\n    rental_period = models.ForeignKey('pricing.RentalPeriod', on_delete=models.SET_NULL, null=True)\n\nclass RentalOrder(models.Model):\n    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)\n    total_amount = models.DecimalField(max_digits=10, decimal_places=2)\n    status = models.CharField(max_length=50, default='pending')\n    created_at = models.DateTimeField(auto_now_add=True)\n\nclass RentalOrderItem(models.Model):\n    order = models.ForeignKey(RentalOrder, related_name='items', on_delete=models.CASCADE)\n    product_id = models.IntegerField()\n    quantity = models.PositiveIntegerField()\n    price = models.DecimalField(max_digits=10, decimal_places=2)\n""",
        "signals.py": """from django.db.models.signals import post_save\nfrom django.dispatch import receiver\nfrom .models import RentalOrder\n\n@receiver(post_save, sender=RentalOrder)\ndef rental_order_saved(sender, instance, created, **kwargs):\n    pass\n""",
        "admin.py": """from django.contrib import admin\nfrom .models import Cart, CartItem, RentalOrder, RentalOrderItem\n\nadmin.site.register(Cart)\nadmin.site.register(CartItem)\nadmin.site.register(RentalOrder)\nadmin.site.register(RentalOrderItem)\n""",
        "serializers.py": """from rest_framework import serializers\nfrom .models import Cart, CartItem, RentalOrder, RentalOrderItem\n\nclass CartItemSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = CartItem\n        fields = '__all__'\n\nclass CartSerializer(serializers.ModelSerializer):\n    items = CartItemSerializer(many=True, read_only=True)\n    class Meta:\n        model = Cart\n        fields = '__all__'\n\nclass RentalOrderItemSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = RentalOrderItem\n        fields = '__all__'\n\nclass RentalOrderSerializer(serializers.ModelSerializer):\n    items = RentalOrderItemSerializer(many=True, read_only=True)\n    class Meta:\n        model = RentalOrder\n        fields = '__all__'\n""",
        "views.py": """from rest_framework import viewsets\nfrom .models import Cart, CartItem, RentalOrder, RentalOrderItem\nfrom .serializers import CartSerializer, CartItemSerializer, RentalOrderSerializer, RentalOrderItemSerializer\n\nclass CartViewSet(viewsets.ModelViewSet):\n    queryset = Cart.objects.all()\n    serializer_class = CartSerializer\n\nclass CartItemViewSet(viewsets.ModelViewSet):\n    queryset = CartItem.objects.all()\n    serializer_class = CartItemSerializer\n\nclass RentalOrderViewSet(viewsets.ModelViewSet):\n    queryset = RentalOrder.objects.all()\n    serializer_class = RentalOrderSerializer\n\nclass RentalOrderItemViewSet(viewsets.ModelViewSet):\n    queryset = RentalOrderItem.objects.all()\n    serializer_class = RentalOrderItemSerializer\n""",
        "urls.py": """from django.urls import path, include\nfrom rest_framework.routers import DefaultRouter\nfrom .views import CartViewSet, CartItemViewSet, RentalOrderViewSet, RentalOrderItemViewSet\n\nrouter = DefaultRouter()\nrouter.register(r'carts', CartViewSet)\nrouter.register(r'cart-items', CartItemViewSet)\nrouter.register(r'orders', RentalOrderViewSet)\nrouter.register(r'order-items', RentalOrderItemViewSet)\n\nurlpatterns = [\n    path('', include(router.urls)),\n]\n"""
    },
    "payments": {
        "__init__.py": "",
        "apps.py": """from django.apps import AppConfig\n\nclass PaymentsConfig(AppConfig):\n    default_auto_field = 'django.db.models.BigAutoField'\n    name = 'apps.payments'\n""",
        "models.py": """from django.db import models\n\nclass Payment(models.Model):\n    order = models.ForeignKey('rentals.RentalOrder', on_delete=models.CASCADE, related_name='payments')\n    amount = models.DecimalField(max_digits=10, decimal_places=2)\n    payment_method = models.CharField(max_length=50)\n    status = models.CharField(max_length=50, default='pending')\n    transaction_id = models.CharField(max_length=100, blank=True, null=True)\n    created_at = models.DateTimeField(auto_now_add=True)\n""",
        "admin.py": """from django.contrib import admin\nfrom .models import Payment\n\nadmin.site.register(Payment)\n""",
        "serializers.py": """from rest_framework import serializers\nfrom .models import Payment\n\nclass PaymentSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = Payment\n        fields = '__all__'\n""",
        "views.py": """from rest_framework import viewsets\nfrom .models import Payment\nfrom .serializers import PaymentSerializer\n\nclass PaymentViewSet(viewsets.ModelViewSet):\n    queryset = Payment.objects.all()\n    serializer_class = PaymentSerializer\n""",
        "urls.py": """from django.urls import path, include\nfrom rest_framework.routers import DefaultRouter\nfrom .views import PaymentViewSet\n\nrouter = DefaultRouter()\nrouter.register(r'payments', PaymentViewSet)\n\nurlpatterns = [\n    path('', include(router.urls)),\n]\n"""
    },
    "deposits": {
        "__init__.py": "",
        "apps.py": """from django.apps import AppConfig\n\nclass DepositsConfig(AppConfig):\n    default_auto_field = 'django.db.models.BigAutoField'\n    name = 'apps.deposits'\n""",
        "models.py": """from django.db import models\nfrom django.conf import settings\n\nclass SecurityDeposit(models.Model):\n    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)\n    order = models.ForeignKey('rentals.RentalOrder', on_delete=models.CASCADE, null=True, blank=True)\n    amount = models.DecimalField(max_digits=10, decimal_places=2)\n    status = models.CharField(max_length=50, default='held') # held, refunded, forfeited\n    created_at = models.DateTimeField(auto_now_add=True)\n    updated_at = models.DateTimeField(auto_now=True)\n\nclass DepositHistory(models.Model):\n    deposit = models.ForeignKey(SecurityDeposit, related_name='history', on_delete=models.CASCADE)\n    action = models.CharField(max_length=50)\n    notes = models.TextField(blank=True)\n    created_at = models.DateTimeField(auto_now_add=True)\n""",
        "admin.py": """from django.contrib import admin\nfrom .models import SecurityDeposit, DepositHistory\n\nadmin.site.register(SecurityDeposit)\nadmin.site.register(DepositHistory)\n""",
        "serializers.py": """from rest_framework import serializers\nfrom .models import SecurityDeposit, DepositHistory\n\nclass DepositHistorySerializer(serializers.ModelSerializer):\n    class Meta:\n        model = DepositHistory\n        fields = '__all__'\n\nclass SecurityDepositSerializer(serializers.ModelSerializer):\n    history = DepositHistorySerializer(many=True, read_only=True)\n    class Meta:\n        model = SecurityDeposit\n        fields = '__all__'\n""",
        "views.py": """from rest_framework import viewsets\nfrom .models import SecurityDeposit, DepositHistory\nfrom .serializers import SecurityDepositSerializer, DepositHistorySerializer\n\nclass SecurityDepositViewSet(viewsets.ModelViewSet):\n    queryset = SecurityDeposit.objects.all()\n    serializer_class = SecurityDepositSerializer\n\nclass DepositHistoryViewSet(viewsets.ModelViewSet):\n    queryset = DepositHistory.objects.all()\n    serializer_class = DepositHistorySerializer\n""",
        "urls.py": """from django.urls import path, include\nfrom rest_framework.routers import DefaultRouter\nfrom .views import SecurityDepositViewSet, DepositHistoryViewSet\n\nrouter = DefaultRouter()\nrouter.register(r'deposits', SecurityDepositViewSet)\nrouter.register(r'deposit-history', DepositHistoryViewSet)\n\nurlpatterns = [\n    path('', include(router.urls)),\n]\n"""
    }
}

for app_name, files in apps_structure.items():
    app_dir = os.path.join(APPS_DIR, app_name)
    os.makedirs(app_dir, exist_ok=True)
    for file_name, content in files.items():
        if not content and file_name == "__init__.py":
            content = "# init\\n"
        with open(os.path.join(app_dir, file_name), 'w') as f:
            f.write(content)

print("Apps created successfully.")
