# Generated by Django 6.1 on 2026-08-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("equipment_needed", models.TextField()),
                (
                    "duration",
                    models.CharField(blank=True, default="1 week", max_length=100),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("estimated_budget", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("CONTACTED", "Contacted"),
                            ("CONVERTED", "Converted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
