# Generated by Django 6.1 on 2026-08-09 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("rentals", "0005_remove_cartitem_legacy_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ORDER_CONFIRMED", "Order Confirmed"),
                    ("PICKUP_READY", "Ready for Pickup"),
                    ("EQUIPMENT_OUT", "Equipment Picked Up"),
                    ("RETURN_DUE", "Return Due Soon"),
                    ("ORDER_RETURNED", "Order Returned"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("DEPOSIT_REFUNDED", "Deposit Refunded"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="rentals.rentalorder",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(),
        ),
    ]
