# Generated by Django 6.1 on 2026-08-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="store",
            name="operating_days",
            field=models.CharField(
                blank=True, default="Monday – Saturday", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="storeproductstock",
            name="reserved_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
