from .base import AIProvider
from decouple import config

class GroqProvider(AIProvider):
    def __init__(self):
        self.api_key = config('GROQ_API_KEY', default='')
        
    def generate_insights(self, data):
        if not self.api_key:
            return "GROQ API Key not configured."
        return "Insights generated by Groq: " + str(data)
