# Generated by Django 6.1 on 2026-08-08 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role_merchant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("RENTER", "Renter"),
                    ("ADMIN", "Admin"),
                    ("MERCHANT", "Merchant"),
                    ("STAFF", "Staff"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RenterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=20, null=True)),
                ("upi_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
