# Generated by Django 6.1 on 2026-08-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_vendorprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lenderprofile",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("ADMIN", "Admin"),
                    ("STAFF", "Staff / Vendor"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="gst_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.DeleteModel(
            name="CustomerProfile",
        ),
        migrations.DeleteModel(
            name="LenderProfile",
        ),
    ]
