# Generated by Django 6.1 on 2026-08-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_lenderprofile_user_alter_user_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorprofile",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
