# Generated by Django 6.1 on 2026-08-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LateFeeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "per_day_rate",
                    models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
                ),
                ("grace_period_hours", models.PositiveIntegerField(default=2)),
                (
                    "max_fee_cap",
                    models.DecimalField(
                        decimal_places=2, default=5000.0, max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Late Fee Configuration",
            },
        ),
        migrations.CreateModel(
            name="RentalPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("days", models.PositiveIntegerField()),
                (
                    "price_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "days"],
            },
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="rentalorderitem",
            name="product_id",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="legacy_product_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="condition_on_return",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GOOD", "Good Condition"),
                    ("DAMAGED", "Damaged"),
                    ("MISSING_ITEMS", "Missing Accessories"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("STORE_PICKUP", "Pick up from Store"),
                    ("DELIVERY", "Standard Delivery"),
                ],
                default="STORE_PICKUP",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="deposit_status",
            field=models.CharField(
                choices=[
                    ("HELD", "Held in Escrow"),
                    ("SETTLED", "Settled"),
                    ("REFUNDED", "Fully Refunded"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                ],
                default="HELD",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="inspection_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="late_fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="late_fee_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="picked_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="rental_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="rental_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="deposit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="legacy_product_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rentalorder",
            name="order_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="rentalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUOTATION", "Quotation"),
                    ("QUOTATION_SENT", "Quotation Sent"),
                    ("RESERVED", "Reserved"),
                    ("PICKED_UP", "Picked Up"),
                    ("ACTIVE", "Active"),
                    ("LATE_RETURN", "Late Return"),
                    ("RETURNED", "Returned"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="RESERVED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rentalorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
