# Generated by Django 6.1 on 2026-08-08 12:58

import apps.rentals.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role_merchant"),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalorder",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="delivery_pincode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="fulfillment_type",
            field=models.CharField(
                choices=[
                    ("DOORSTEP", "Doorstep Delivery"),
                    ("STORE_PICKUP", "Store Pickup"),
                ],
                default="DOORSTEP",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rental_orders",
                to="accounts.merchant",
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="pickup_code",
            field=models.CharField(
                blank=True,
                default=apps.rentals.models.generate_pickup_code,
                max_length=10,
            ),
        ),
    ]
