# Generated by Django 6.1 on 2026-08-08 15:51

import apps.rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_rentalorder_delivery_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalorder",
            name="order_number",
            field=models.CharField(
                blank=True,
                default=apps.rentals.models.generate_order_number,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="rentalorder",
            name="status",
            field=models.CharField(default="ACTIVE", max_length=50),
        ),
    ]
