# Generated by Django 6.1 on 2026-08-08 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_latefeeconfig_rentalperiod_and_more"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="pickup_slot",
            field=models.CharField(blank=True, default="MORNING_10_1", max_length=50),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="pickup_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="pickup_slot",
            field=models.CharField(
                choices=[
                    ("MORNING_10_1", "Morning (10:00 AM – 01:00 PM)"),
                    ("AFTERNOON_2_6", "Afternoon (02:00 PM – 06:00 PM)"),
                    ("EVENING_6_9", "Evening (06:00 PM – 09:00 PM)"),
                ],
                default="MORNING_10_1",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rental_orders",
                to="stores.store",
            ),
        ),
    ]
