# Generated by Django 6.1 on 2026-08-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_cart_store_cartitem_pickup_slot_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RentalPeriod",
        ),
    ]
