# Generated by Django 6.1 on 2026-08-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0004_delete_rentalperiod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="legacy_product_id",
        ),
        migrations.RemoveField(
            model_name="rentalorderitem",
            name="legacy_product_id",
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rentalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUOTATION", "Quotation"),
                    ("QUOTATION_SENT", "Quotation Sent"),
                    ("RESERVED", "Reserved"),
                    ("PICKED_UP", "Picked Up"),
                    ("LATE_RETURN", "Late Return"),
                    ("RETURNED", "Returned"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="RESERVED",
                max_length=30,
            ),
        ),
    ]
